#!/usr/bin/perl

use DBI;

$dbh = DBI->connect('DBI:mysql:maxima:localhost:3306','root','bartok26') || die $DBI::errstr ; 
$dbh->{RaiseError} = 1;
$dbh->do("set names cp1250");

$group_name="permissionb2b";
$group_id=1304;

$sql="select ui_cegnev,ui_post_code_company,ui_street_name_company,ui_street_number_company,id from users_$group_name where validated='yes' and robinson='no' and bounced='no'";
$sth = $dbh->prepare($sql);
$sth->execute;

print "$sql\n";

$i = 0;

$mfile="shobertb2b";
open (OO,">$mfile");

while (@r = $sth->fetchrow_array) {
    $i++;
    if ($i/100 == int($i/100)) {
        print "$i\n";
    }
    $id=$r[4];
    $mc = mx_wund_match($r[0]);
    $mc .= mx_num($r[1]);
    $mc .= mx_wund_match($r[2]);
    $mc .= mx_num($r[3]);

#CÉGNÉV mezõbõl az elsõ szó ékezetlenítve, betûkön és számokon kívül minden egyéb karakter kidobálva.
#IRÁNYÍTÓSZÁM
#UTCA mezõbõl az elsõ szó ékezetlenítve, betûkön és számokon kívül minden egyéb karakter kidobálva.
#CÍM mezõbõl az elsõ szám.


    print OO "$mc,$id\n";
}
close OO;

sub mx_num($) {

    $num=shift;
    if ($num =~ /^[^0-9]*([0-9]+)/) {
        return $1;
    }
}

sub mx_wund_match($) {

    my $strall=shift;

    @words=split(/ /,$strall);

    $str=@words[0];

    $str =~ s/Á/A/g;
    $str =~ s/É/E/g;
    $str =~ s/Í/I/g;
    $str =~ s/Ó/O/g;
    $str =~ s/Ö/O/g;
    $str =~ s/Õ/O/g;
    $str =~ s/Ú/U/g;
    $str =~ s/Ü/U/g;
    $str =~ s/Û/U/g;
    $str =~ s/á/a/g;
    $str =~ s/é/e/g;
    $str =~ s/í/i/g;
    $str =~ s/ó/o/g;
    $str =~ s/ö/o/g;
    $str =~ s/õ/o/g;
    $str =~ s/ú/u/g;
    $str =~ s/ü/u/g;
    $str =~ s/û/u/g;

    $str =~ s/[^a-zA-Z0-9]//g;
    
    return $str;
}
