#!/usr/bin/perl

use DBI;

$dbh = DBI->connect('DBI:mysql:maxima:localhost:3306','root','bartok26') || die $DBI::errstr ; 
$dbh->{RaiseError} = 1;
$dbh->do("set names cp1250");

@filters = (15515);

for (@filters) {

    $filter_id=$_;
    $group_name="permission";
    $group_id=543;

    $filter_error="filter_ok";
    $filtres="";
    open FILTER, "/usr/local/maxima/filter_engine $filter_id|";
    while (<FILTER>) {
        $filtres .= $_;
    }
    close (FILTER);
    @filtarr = split /\n/,$filtres;
    if ($filtarr[0] eq "filter_ok") {
            $filter_query=$filtarr[1];
            $limitord=$filtarr[2];
            $limitnum=$filtarr[3];
            $syntax_error=$filtarr[4];
            $syntax_error_text=$filtarr[5];
    }
    else {
            $filter_error="error in filter engine: $filtarr[0]";
            print "$filter_error\n";
            exit;
    }

    if (length($limitord)) { 
          $limitexp=" order by $limitord limit $limitnum";
    }
    else {
          $limitexp="";
    }
    $sql="select id,ui_vezeteknev,ui_keresztnev,ui_ir,ui_utca_nev,ui_hazszam,ui_nem from users_$group_name where validated='yes' and ($filter_query) and robinson='no' and bounced='no' $limitexp";
    $sth = $dbh->prepare($sql);
    $sth->execute;

    print "$sql\n";

    $i = 0;

    $mfile="sos$filter_id";
    open (OO,">$mfile");

    while (@r = $sth->fetchrow_array) {
        $i++;
        if ($i/100 == int($i/100)) {
            print "$i\n";
        }
        $id=$r[0];
        $mc = mx_massal($r[1],4);
        $mc .= mx_massal($r[2],2);
        $mc .= mx_num($r[3]);
        $mc .= mx_massal($r[4],2);
        $mc .= mx_num($r[5]);
        if ($r[6] eq ",14," or $r[6] eq "14") {
            $mc .= "F";
        }
        elsif ($r[6] eq ",15," or $r[6] eq "15") {
            $mc .= "N";
        }
        else {
            $mc .= " ";
        }

#A magánszemélyeknél a MATCH kód felépítése a következ:  
#Vezetéknév: els 4 mássalhangzó (jobbról 'space'-szel töltve - pl. Ha az illett Gálnak hívják, akkor a 'g' és 'l' bet után két 'space jön)
#Keresztnév: els 2 mássalhangzó (jobbról 'space'-szel töltve)
#Irányítószám: 4 karakter (balról '0'-val töltve)
#Utcanév: els 2 mássalhangzó (jobbról 'space'-szel töltve)
#Házszám: 4 karakteren, (balról '0'-val töltve -  pl.: ha a házszám 3. , akkor a kód 0003)
# 
#Utolsó karakter:
#N (ha n)
#F (ha férfi)
#
#Összesen 17 karakterbl áll. (az utolsóval együtt - ld. I/N/F) 


        print OO "$mc,$id\n";
    }
close OO;
}

sub mx_num($) {

    $num=shift;
    $num=~s/[^0-9]//g;
    $lnl=length($num);
    if ($lnl<4) {
        for ($i=0;$i<4-$lnl;$i++) {
            $num="0$num";
        }
    }
    return substr($num,0,4);
}

sub mx_massal($;$) {

    my $str=shift;
    my $num=shift;

    $str =~ s/[^bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ]//g;

    $sub = substr(uc($str),0,$num);
    $lnl=length($sub);
    if ($lnl<$num) {
        for ($i=0;$i<$num-$lnl;$i++) {
            $sub="$sub ";
        }
    }
    
    return $sub;
}
