<html>
	<head>
	    <title>Maxima</title>
			<script type="text/javascript">
			
			try {
        console.log();
      }catch(e){
        if(e)
          console.log = function() {}
      };
			
			/*var head = document.getElementsByTagName("script")[0].parentNode,
			main 			= document.createElement("script"),
			extBase	 	= document.createElement("script"),
			cssExt 		= document.createElement("link"),
			cssStyle 	= document.createElement("link");
			
			cssStyle.setAttribute("type", "text/css");
			cssStyle.setAttribute("rel", 	"stylesheet");
			cssStyle.setAttribute("href", "css/style.css");
			cssExt.setAttribute("type", 	"text/css");
			cssExt.setAttribute("rel", 		"stylesheet");
			cssExt.setAttribute("href", 	"../../ext-4.0.2a/resources/css/ext-all.css");
			extBase.setAttribute("type", 	"text/javascript");
			extBase.setAttribute("src", 	"../../ext-4.0.2a/ext-all.js");
			main.setAttribute("type", 		"text/javascript");
			main.setAttribute("src", 			"js/build/main-debug.js");
			head.appendChild(cssExt);
			head.appendChild(cssStyle);
			head.appendChild(extBase);
			head.appendChild(main);*/
			</script>  
	    <!--link rel="stylesheet" type="text/css" href="../ext-4.0.2a/resources/css/ext-all.css"-->
	    
	    <link rel="stylesheet" type="text/css" href="http://extjs.cachefly.net/ext-4.0.2a/resources/css/ext-all.css">
	    
	    <script type="text/javascript" src="../ext-4.0.2a/ext-all.js"></script>
	    <script type="text/javascript" src="js/build/main-debug.js"></script>
	</head>
	<body></body>
</html>
