Amazon:
  item: "//item"
  author: "//author"
  title: "//title"
  detailpageurl: "//detailpageurl"
  mediumimage: "//mediumimage//url"
  publicationdate: "//publicationdate"
  releasedate: "//releasedate"
  publisher: "//publisher"
  ean: "//ean"
  isbn: "//isbn"
  lowestnewprice: "//lowestnewprice//formattedprice"
Bookline:
  item: "//div[@class='comp_search_results']//div"
  matcher: "comp_product_displayproduct_search"
  linkToTheProduct: "//div[@class='image']//a"
  author: "//div[@class='maindata']//h2"
  title: "//div[@class='maindata']//h1"
  img: "//div[@class='product-info']//a[@class='popup']//img"
  publicationdate: "//div[@class='maindata']//h3"
  isbn: "//div[@class='maindata']//li"
  price: "//div[@class='priceblockleft']//strong"
Wikipedia:
  item: "//table"
  matcher: "infobox"
  nameSpan: "//span[@class='fn']"
  nameTh: "//th[@class='fn']"

