{
  xtype: 'viewport',
  border: 0,
  margin: 0,
  padding: 0,
  style: 'background: #EBEEF2;',
  maintainFlex: true,
  renderTo : Ext.getBody(),
  layout: { type: 'fit'
    /*align: 'stretch',
    type: 'hbox'*/
  },
  items: [{
    id: 'translateContainer',
    xtype: 'container',
    margin: 20,
    /*height    : 600,
    width     : 1100,*/
    layout: {
      align: 'stretch',
      type: 'hbox'
    },
    items:[{
      xtype   : 'grid',
      title   : 'Translate',
      id      : "Iddqd",
      store   : self.store,
      columns : [
        {header : 'id'               , dataIndex: 'id'},
        {header : 'Kategória'        , dataIndex: 'category'},
        {header : 'Változó'          , dataIndex: 'variable'},
        {header : 'Kifejezés'        , dataIndex: 'word', renderer : this.renderer, editor : {xtype: 'textfield',allowBlank: false}},
        {header : 'Idegen kifejezés' , dataIndex: 'foreign_word', renderer : this.renderer, editor : {xtype: 'textfield',allowBlank: false}}
      ],
      plugins: [self.rowEditing],
      /*height    : 400,
      width     : 700,*/
      layout: {
        type: 'fit'
      },
      dockedItems: [{
        xtype       : 'pagingtoolbar',
        store       : self.store,
        dock        : 'top',
        displayInfo : true,
        displayMsg  : 'Találatok: {0} - {1} of {2}',
        emptyMsg    : "Nincs találat."
      }]
      }, {
        xtype   : 'container',
        id      : "rightside",
        height  : 400,
        width   : 350,
        layout: {
          align: 'stretch',
          type: 'vbox'
        },
      items: [{
        xtype   : 'panel',
        title   : 'Languages',
        height  : 100,
        width   : 200,
        layout  : {
          type: 'fit'
        },
        items: [{
          xtype: 'combo',
          id: 'languages',
          fieldLabel: 'Choose language',
          store: self.langStore,
          queryMode: 'local',
          displayField: 'lang',
          valueField: 'langval',
          triggerAction : 'all'
        }]
      },{
        xtype   : 'panel',
        title   : 'Categories',
        height  : 100,
        width   : 200,
        layout  : {
          type: 'fit'
        },
        items: [{
          xtype: 'combobox',
          id: 'categories',
          fieldLabel: 'Choose Categoriy',
          store: self.catStore,
          queryMode: 'local',
          displayField: 'cat',
          valueField: 'catval',
          triggerAction : 'all'   
        }]
      }]
    }]
}]}